---

- name: Params > File
  lineinfile:
    dest:   "{{ manala_shorewall_params_file }}"
    regexp: "^{{ (item.keys()|list)[0] }}="
    line:   "{{ (item.keys()|list)[0] }}={{ (item.values()|list)[0] }}"
  with_items: "{{ manala_shorewall_params }}"
  notify:
    - shorewall restart
